name: Release

on: workflow_dispatch

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup
        uses: actions/setup-node@v4
        with:
          cache: yarn
          node-version: 22
      - name: Install
        run: yarn --immutable
      - name: Build
        run: yarn build
      - name: Login to NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc
      - name: Release
        run: yarn semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Get new version
        run: |
          echo "NEW_VERSION=$(npm pkg get version | sed 's/"//g')" >> "$GITHUB_ENV"
          echo "NEW_VERSION=$NEW_VERSION"
      - name: Import GPG key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          git_config_global: true
          git_commit_gpgsign: true
          git_user_signingkey: true
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          trust_level: ultimate
      - name: Add, Commit & Push
        run: |
          # https://github.com/orgs/community/discussions/26580#discussioncomment-3281023
          git config --global url.https://${{ secrets.GH_TOKEN }}@github.com/.insteadOf https://github.com/
          git config --global user.email "ivan.gabriele+github@protonmail.com"
          git config --global user.name "Ivan Gabriele (Github)"
          git add .
          git commit -m "ci(release): v${{ env.NEW_VERSION }}"
          git push
